export const GAME_CONFIG = {
  INITIAL_LEVEL: 1,
  INITIAL_SCORE: 0,
  DURATION: 3.0,
  TIMER_INTERVAL_MS: 30,
  INPUT_FOCUS_DELAY_MS: 100,
  BASE_DIGIT_COUNT: 4,
};

export const GAME_PHASES = {
  GENERATE: 'GENERATE',
  SHOW:     'SHOW',
  CHECK:    'CHECK',
  RESULT:   'RESULT',
};